extern "C" {
  #include "../pqm4/crypto_kem/sikep751/m4/api.h"
  const String CRYPTO_KEM_ALGNAME = CRYPTO_ALGNAME;
  const int CRYPTO_KEM_SECRETKEYBYTES = CRYPTO_SECRETKEYBYTES;
  const int CRYPTO_KEM_PUBLICKEYBYTES = CRYPTO_PUBLICKEYBYTES;
  const int CRYPTO_KEM_BYTES = CRYPTO_BYTES;
  const int CRYPTO_KEM_CIPHERTEXTBYTES = CRYPTO_CIPHERTEXTBYTES;

  #undef CRYPTO_PUBLICKEYBYTES
  #undef CRYPTO_SECRETKEYBYTES
  #undef CRYPTO_BYTES
  #undef CRYPTO_ALGNAME
  #undef CRYPTO_CIPHERTEXTBYTES

  #include "../pqm4/crypto_sign/falcon-1024/m4-ct/api.h"
  const String CRYPTO_SIGN_ALGNAME = CRYPTO_ALGNAME;
  const int CRYPTO_SIGN_PUBLICKEYBYTES = CRYPTO_PUBLICKEYBYTES;
  const int CRYPTO_SIGN_SECRETKEYBYTES = CRYPTO_SECRETKEYBYTES;
  const int CRYPTO_SIGN_BYTES = CRYPTO_BYTES;

  #undef CRYPTO_PUBLICKEYBYTES
  #undef CRYPTO_SECRETKEYBYTES
  #undef CRYPTO_BYTES
  #undef CRYPTO_ALGNAME

  #include "randombytes.h"
  //#include "hal.h"
}

#define MESSAGE_LENGTH  (CRYPTO_KEM_PUBLICKEYBYTES + CRYPTO_SIGN_BYTES)
#define SMLEN_BYTES     4
